- defaults:
    link:
      relink: true

- clean: ['~']

- link:
    ~/.zshrc: zshrc
    ~/.vimrc: vimrc
    ~/.config/nvim/init.vim: init.vim
    ~/.bashrc: bashrc

- shell:
  - [git submodule update --init --recursive, Installing submodules]
